### ISSUE TITLE
Can't scroll page using keyboard

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/ddm-menu#7]
Quoting original [issue from ksl-header](https://github.com/deseretdigital-ui/ksl-header/issues/36#issuecomment-72540791):

> When page loads you can't scroll using the keyboard (arrow keys, space bar, page up/down, etc.). If you press tab so that the header widget is focused, you still can't scroll with the keyboard. If the mouse pointer is over the header, you can't scroll using the mouse wheel. Only way to scroll with keyboard is if you unfocus the header (clicking another element or tabbing away from it). Same with mouse wheel.

**Comment by jehoshua02** [comment]
Playing around in the console on the demo page, I've determined that calling `$('.ddm-menu-container__content').focus()` allows scrolling the content. It could be a solution, but for now I count it a clue, since it may interfere with other javascript on the page that is attempting to set focus on a particular element.

**Comment by jehoshua02** [comment]
Whatever the solution, I believe it will require a pull request on ddm-menu and it should be considerate of the page on which the ddm-menu is being used.

**Comment by jehoshua02** [comment]
@formigone We are all in a meeting for the next three days and not sure where this fits in with all other priorities so it might take some time to get to it.

I was able to reproduce in IE11 on WinXP. Also Firefox and Chrome on Mac.

1. Load the [ddm-menu demo page](http://ui.deseretdigital.com/ddm-menu/).
2. Arrow up, arrow down, page up, page down, space bar, top, bottom, etc.

None of the keyboard actions cause scrolling like expected.

**Comment by janiv** [comment]
Fixed in #8.
